export enum ESocketEventName {
  AUTHENTICATED = 'AUTHENTICATED',
  JOIN_ADMIN_ROOM = 'JOIN_ADMIN_ROOM',
  JOIN_PERSONAL_ROOM = 'JOIN_PERSONAL_ROOM',
  LEAVE_ROOM = 'LEAVE_ROOM',
  CART_UPDATED = 'CART_UPDATED',
  ERROR = 'ERROR',
}
